version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: visitor_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: visitor_tracking
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: